version: '3.8'
name: 'workouts-go'

services:
  web:
    build:
      context: docker/web
      dockerfile: Dockerfile
    working_dir: /web
    volumes:
      - ./web:/web
      - /web/node_modules
    ports:
      - "127.0.0.1:8080:8080"

  trainer-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    #      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/trainer
    ports:
      - "127.0.0.1:3000:$PORT"
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
    depends_on:
      - mysql

  trainer-grpc:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    #      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/trainer
    ports:
      - "127.0.0.1:3010:$PORT"
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: grpc
      GOCACHE: /go-cache
    depends_on:
      - mysql

  trainings-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    #      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/trainings
    ports:
      - "127.0.0.1:3001:$PORT"
    env_file:
      - .env
    environment:
      GOCACHE: /go-cache
    depends_on:
      - mysql

  users-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    #      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/users
    ports:
      - "127.0.0.1:3002:$PORT"
    environment:
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
    env_file:
      - .env
    depends_on:
      - mysql

  users-grpc:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    #      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/users
    ports:
      - "127.0.0.1:3020:$PORT"
    environment:
      SERVER_TO_RUN: grpc
      GOCACHE: /go-cache
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    env_file:
      - .env
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "127.0.0.1:3306:3306"
    restart: unless-stopped

  mysql-components-test:
    image: mysql:8
    env_file:
      - .env
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "127.0.0.1:3306:3306"
    restart: unless-stopped